permalink: pretty
markdown: rdiscount
highlighter: pygments

baseurl:             /playbook

collections:
  - plays

sass:
  sass_dir:          _scss
  style:            :compressed

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/wearethoughtfox/playbook/
